### ISSUE TITLE
Running the scannet dataset reported an error, but running the replica and tum datasets did not report an error

### ISSUE THREAD

**Issue by YIXIN-M** [eriksandstroem/Point-SLAM#35]
(base) yixin@yixin-miao:~/下载/Point-SLAM$ conda activate point-slam
(point-slam) yixin@yixin-miao:~/下载/Point-SLAM$ python run.py configs/ScanNet/scene0000.yaml

⭐️ INFO: The output folder is output/ScanNet/scene0000/20240815_192937
⭐️ INFO: The GT, generated and residual depth/color images can be found under output/ScanNet/scene0000/20240815_192937/tracking_vis/ and output/ScanNet/scene0000/20240815_192937/mapping_vis/
⭐️ INFO: The mesh can be found under output/ScanNet/scene0000/20240815_192937/mesh/
⭐️ INFO: The checkpoint can be found under output/ScanNet/scene0000/20240815_192937/ckpt/
Process mapper:
Traceback (most recent call last):
  File "/home/yixin/anaconda3/envs/point-slam/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/yixin/anaconda3/envs/point-slam/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yixin/下载/Point-SLAM/src/Point_SLAM.py", line 187, in mapping
    self.mapper.run(time_string)
  File "/home/yixin/下载/Point-SLAM/src/Mapper.py", line 660, in run
    _, gt_color, gt_depth, gt_c2w = self.frame_reader[0]
  File "/home/yixin/下载/Point-SLAM/src/utils/datasets.py", line 88, in __getitem__
    color_path = self.color_paths[index]
IndexError: list index out of range

**Comment by eriksandstroem** [comment]
Hi,
Sorry for the late reply. Did you solve it? Usually it is your folder structure that is wrong when this happens. A folder called "frames" is expected to be nested for the ScanNet dataset.

**Comment by YIXIN-M** [comment]
Thank you for your suggestions and methods, which helped me solve my problem. Thank you！！！
