### ISSUE TITLE
Mesh error

### ISSUE THREAD

**Issue by RoseWillow** [eriksandstroem/Point-SLAM#9]
Evaluating reconstruction...
Traceback (most recent call last):
  File "/home/dnc/Point-SLAM/src/tools/get_mesh_tsdf_fusion.py", line 353, in <module>
    main()
  File "/home/dnc/Point-SLAM/src/tools/get_mesh_tsdf_fusion.py", line 194, in main
    slam = Point_SLAM(cfg, args, share_npc=False,
  File "/home/dnc/Point-SLAM/./src/Point_SLAM.py", line 99, in __init__
    self.npc = NeuralPointCloud(cfg)
  File "/home/dnc/Point-SLAM/./src/neural_point.py", line 38, in __init__
    self.index = faiss.index_cpu_to_gpu(self.resource,
  File "/home/dnc/anaconda3/envs/point-slam/lib/python3.10/site-packages/faiss/swigfaiss.py", line 10275, in index_cpu_to_gpu
    return _swigfaiss.index_cpu_to_gpu(provider, device, index, options)
RuntimeError: Error in virtual void* faiss::gpu::StandardGpuResourcesImpl::allocMemory(const faiss::gpu::AllocRequest&) at /project/faiss/faiss/gpu/StandardGpuResources.cpp:452: Error: 'err == cudaSuccess' failed: StandardGpuResources: alloc fail type TemporaryMemoryBuffer dev 0 space Device stream 0x397eefa0 size 1073741824 bytes (cudaMalloc error out of memory [2])

**Comment by RoseWillow** [comment]
My GPU device is RTX2060 6GB.
Is this caused by insufficient GPU memory?

**Comment by eriksandstroem** [comment]
Hi @RoseWillow,
It would appear so, yes. We ran our experiments on 12 GB GPUs.

**Comment by RoseWillow** [comment]
Thank you for your reply!
